### ISSUE TITLE
忘記填Google表單

### ISSUE THREAD

**Issue by ycs18153** [compiler-s21/discussion#19]
老師您好@ypyou ，
不好意思我忘記填寫您之前發布的Google表單，剛剛要填卻發現已經過期了。
因為擔心之後還是得在課堂中要求老師確認權限會造成大家的困擾，
所以希望老師那邊還能再將我的mail加入，
email address: twlin.iim09g@nctu.edu.tw
感激不盡！

**Comment by ypyou** [comment]
@ycs18153, the form is still opened.
