### ISSUE TITLE
[Test Case] VariableReference.p

### ISSUE THREAD

**Issue by minchuncho** [compiler-s21/discussion#23]
助教，您好：

我想請問測資 VariableReference.p 的第 23、24 行。
不知道是不是我有遺漏，但就我目前了解，`a` 並不是 array，那判斷 `// [ERROR] over subscript` 是什麼依據呢？

謝謝。

**Comment by Naetw** [comment]
確實不太精準，嚴格來說 `a` 因為不是 array 所以在語意上不算 array reference，但在語法上是屬於 array reference（符合 array reference 的特徵）。目前這邊的判斷依據是：因為 `a` 不屬於 array 所以 dimensions 為 0（想像成 `int a[0]`），而 23, 24 行的 `a[40][50][60]` 超出了 `a` 所擁有的 dimensions 數量，所以 over subscript。

這行測資改為 `arr[40][50][60]` 確實會比較合適，或甚至是加入新的語意錯誤：「對一個非 array 變數做 subscripting」。

@minchuncho 感謝回報，這項改動會在之後的學期使用，這學期還請先以上面模糊的判斷方式進行作業實作。

**Comment by minchuncho** [comment]
了解，謝謝助教！
