### ISSUE TITLE
[Test case] 1_table

### ISSUE THREAD

**Issue by minchuncho** [compiler-s21/discussion#26]
助教，您好：

我想問測資 1_table 的第 25-29 行，`funcWith2Parameters(p1 : real; p2 : array 2 of real) : real` 要 `return real`，但是並沒有 return。
又 1_table 是完全正確的測資，所以在處理 return type 時想不通，這個是特例嗎？還是我有遺漏什麼規則？謝謝！

```
25: funcWith2Parameters(p1 : real; p2 : array 2 of real) : real
26: begin
27:     var constant : 19.25;
28: end
29: end
```

**Comment by Naetw** [comment]
之前在設計語意規則時基本上是參考 C 語言，在 C 語言裡，需要回傳值但沒有回傳的陳述式時的處理方式是用警告 (warning) 而非錯誤 (error)，又我們作業基本上只有針對「錯誤」去要求同學去處理，所以需要回傳但沒有回傳的案例就沒特別規範了。

@minchuncho 感謝回報，因為這部分沒特別規範，所以之後會補上回傳陳述式以避免造成同學疑惑。這項改動一樣會在之後的學期使用。
