### ISSUE TITLE
HW5 執行問題

### ISSUE THREAD

**Issue by Jepyagg** [compiler-s21/discussion#29]
spec裡面有提到要執行某.p檔案要用
Execute: ./compiler [input file] --save-path [save path]
可是makefile好像不會做出叫做compiler的執行檔
是不是怪怪的

另外
我做make test的時候
output_riscv_code的資料夾是完全沒東西
自己用./parser [input file] --save-path [save path]的時候
最少都會做一個空的.S檔出來

以上 希望能解答一下

**Comment by ran-ablaze** [comment]
因為此次的 src/Makefile 還未提供，所以你產生出來的檔案名稱跟跟 spec 上面不同是正常的
make test 部分應該也是檔案名稱不同的問題所導致
可以自行把 Makefile 的輸出檔名改成 compiler 或是等 source code 釋出之後的 Makefile 拿來使用即可
