### ISSUE TITLE
macro 修改

### ISSUE THREAD

**Issue by u1f383** [compiler-s21/discussion#3]
助教你好，

想請問 spec 中：

There are four C macro definitions in the starter code src/scanner.l: token,　tokenChar, and tokenString. You should write your scanner actions using the aforementioned macros or any other ones you defined in this manner for implementing the token listing option.

此段說明意思是指我們必須在 scanner.l 中的開頭那 3 (or 4) 個與 token 有關的 macro，都不能做更動的情況下完成本次作業嗎？

**Comment by u1f383** [comment]
還想問一下，除此了提到的 macro 之外，整份程式碼哪些部分可以改、哪些部分不行改，謝謝。

**Comment by ran-ablaze** [comment]
@u1f383 
程式碼均可以做更改，只要最後make test出來的結果正確即可。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
