### ISSUE TITLE
範例 assembly code 檔相關疑問

### ISSUE THREAD

**Issue by u1f383** [compiler-s21/discussion#31]
助教你好，

想請問 README 中 "Combining All Examples Above" 內的 assembly code 是否為用 compiler 程式執行產生出來的？其中部分內容有發現做相同的事情但是兩段程式碼長得不一樣，看起來像是手動加上的，由於做作業時多少會參考那份程式碼，因此想確定一下避免設計方向搞錯。

謝謝。

**Comment by chrisPyr** [comment]
@u1f383 

同學你好，關於那部份的code，基本上是從上面各個例子複製組合過來的，可能同學發現有錯誤的地方？有的話可以提出來。
如果同學要參考的話，可以先看上面各個例子就好。
