### ISSUE TITLE
.S檔輸出問題

### ISSUE THREAD

**Issue by laiyousin** [compiler-s21/discussion#35]
助教您好，我在生成.S檔案時會出現輸出不完全的情況，想請問何種狀況會出現此種問題？
![image](https://user-images.githubusercontent.com/68462169/122942822-10387000-d3a9-11eb-89ea-634f41957930.png)
(應出現mv t0, a0    #move value in a0 to t0(a0 from function))
謝謝助教。

**Comment by 5fe6eb50c7aa19f9** [comment]
@laiyousin 

正常來說不會這樣，
有可能是你在其他地方輸出了一些特殊的ascii所導致。

**Comment by laiyousin** [comment]
找到問題了，謝謝助教~
