### ISSUE TITLE
printInt

### ISSUE THREAD

**Issue by laiyousin** [compiler-s21/discussion#36]
助教您好，想請問為何我已執行riscv32-unknown-elf-gcc [generated RISC-V assembly file] io.c -o [output ELF file]
但依然出現下列訊息
![image](https://user-images.githubusercontent.com/68462169/123056100-22fa8580-d439-11eb-8c52-ad03f5826f53.png)
謝謝助教~

**Comment by Naetw** [comment]
你截圖中的第一行命令就已經把執行檔編譯好了，不用再執行你的第二個命令。

```
riscv32-unknown-elf-gcc [generated RISC-V assembly file] io.c -o [output ELF file] 
```

你第二個命令做的事是把 `io.c` 從上面這個命令中拿掉然後去編譯成執行檔，所以連結器 (linker, ld) 會找不到 `printInt`，因為你把 `io.c` 拿掉了。

**Comment by laiyousin** [comment]
了解了~
但執行完後會出現以下結果
![image](https://user-images.githubusercontent.com/68462169/123063554-1d546e00-d440-11eb-9d29-dfab8f9f654c.png)
user load segfault，想請問此錯誤的原因，謝謝助教

**Comment by Naetw** [comment]
這個需要自己去看產生出來的 RISC-V 指令是否有錯誤，以測資的內容來說，可能的原因有：

- 你對非記憶體的數值做 dereference，像是透過 sp 拿到某個區域變數的位址之後，再透過 `lw` 做 dereference 取得該位址上的數值後，後續利用時又把該數值當作記憶體位址去用 `lw` 做 dereference
- 區域變數應該至少要從 `-12(s0)` 開始擺放，若從 `-8(s0)` 可能會改壞前一個函式的 frame pointer 導致函式 return 後 frame pointer 歪掉，後續透過 frame pointer 的存取就容易出現錯誤

你可能需要把功能一個個移除做測試，像是你可能已經完成 expression 的測資，然後往下實做下一個測資 function 的時候出問題，那就往你針對 function 功能所產生出來的 RISC-V 指令去做檢查。

另外一個幫助除錯的方法是，針對每個 construct (e.g., print statement, for statement) 在對應的 `visit` 函式裡的開頭跟結尾額外輸出註解到 `.S` 檔來圈出某一段指令是針對 print 所產生的指令、另一段指令是針對 for 所產生出來的指令等等，好幫助你在長長 RISC-V 指令中更快地找到要檢查的地方。

**Comment by laiyousin** [comment]
好的謝謝!
