### ISSUE TITLE
Midterm exam on April 13

### ISSUE THREAD

**Issue by ypyou** [compiler-s21/discussion#6]
Hello @compiler-s21/2021s-students, the midterm exam will be held on April 13. 

Detail information about the exam:
Date: April 13
Time: ~~10:10-12:00~~ 13:20-15:10
Location: ED102
Scope: Chapters 1, 3, and 4

**Comment by thisismingggg** [comment]
老師您好：

因為這個時間我有其他課程沒辦法參加考試，請問可以另外跟助教安排其他時間補考嗎？

資工11 張祐銘

**Comment by minchuncho** [comment]
老師您好：
我該時段也有其他課程，無法參加期中考，是否能改其他時段或補考呢？

**Comment by EtBLh** [comment]
老師您好：
我該時段也有其他課程，無法參加期中考，請問可以改其他時段或安排補考嗎？

**Comment by ypyou** [comment]
My mistake. The exam should be held during the regular lecture time.

@compiler-s21/2021s-students 
The exam time was mistakenly written.  The correct time should be as follows.
Date: April 13
Time: 13:20-15:10
